# -*- coding: utf-8 -*-
"""Penyelesaian Integral menggunakan Metode Trapezoid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eoCaah2VtclekL0WVJeVfILFvvdWVa9h
"""

# Penyelesaian Integral menggunakan Metode Trapezoid 
# n = 10

import numpy as np
import matplotlib.pyplot as plt

def func(x):
    return (x**2)*np.exp(-x)

a = 1.0

b = 10.0
n = 10

dx = (b-a)/(n-1)
x = np.linspace(a,b,n)

sigma = 0
for i in range (1, n-1):
    sigma += func(x[i])
    
hasil = 0.5*dx*(func(x[0])+2*sigma+func(x[-1]))

print (hasil)

xp =np.linspace(a,b)
plt.plot(xp,func(xp))

for i in range (n):
    plt.bar(x[i],func(x[i]), align = 'edge',width = 0.000001, color = 'gray', edgecolor = 'blue')

plt.fill_between(x,func(x),color= 'yellow')

plt.show()

# Penyelesaian Integral menggunakan Metode Trapezoid 
# n = 100

import numpy as np
import matplotlib.pyplot as plt

def func(x):
    return (x**2)*np.exp(-x)

a = 1.0
b = 10.0
n = 100

dx = (b-a)/(n-1)
x = np.linspace(a,b,n)

sigma = 0
for i in range (1, n-1):
    sigma += func(x[i])
    
hasil = 0.5*dx*(func(x[0])+2*sigma+func(x[-1]))

print (hasil)

xp =np.linspace(a,b)
plt.plot(xp,func(xp))

for i in range (n):
    plt.bar(x[i],func(x[i]), align = 'edge',width = 0.000001, color = 'gray', edgecolor = 'blue')

plt.fill_between(x,func(x),color= 'yellow')

plt.show()

# Penyelesaian Integral menggunakan Metode Trapezoid 
# n = 1000

import numpy as np
import matplotlib.pyplot as plt

def func(x):
    return (x**2)*np.exp(-x)

a = 1.0
b = 10.0
n = 1000

dx = (b-a)/(n-1)
x = np.linspace(a,b,n)

sigma = 0
for i in range (1, n-1):
    sigma += func(x[i])
    
hasil = 0.5*dx*(func(x[0])+2*sigma+func(x[-1]))

print (hasil)

xp =np.linspace(a,b)
plt.plot(xp,func(xp))

for i in range (n):
    plt.bar(x[i],func(x[i]), align = 'edge',width = 0.000001, color = 'gray', edgecolor = 'blue')

plt.fill_between(x,func(x),color= 'yellow')

plt.show()